name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-16.04
    container:
    image:  alpine:latest

    steps:
    - run:
    - uses: actions/checkout
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

